#!/bin/bash
# Simple wrapper to speed up dumping games into their separate files into the Dumps directory
# Called with the game's name
# ./dump_game ../Games/awaken.z5

if [ $# -eq 0 ]
    then
        echo "Please supply the game's name"
        exit 1
fi

../ZTools/infodump -o $1 > ../Dumps/$(basename $1)_object_dump
../ZTools/infodump -t $1 > ../Dumps/$(basename $1)_object_tree_dump
../ZTools/infodump -d $1 > ../Dumps/$(basename $1)_dict_dump
../ZTools/infodump -g $1 > ../Dumps/$(basename $1)_verb_dump

../ZTools/txd -dns $1 > ../Dumps/$(basename $1)_txd_dump